post-message-for-puppet-walnut
wechaty/jekyll pull request #116
Opened 2022-04-20 11:19 UTC by fabian4

2022-04-21 06:19 UTC, su-chang commented on jekyll/_posts/2022-04-20-post-message-for-puppet-walnut.md
> +  .on('message',       async (message: { toContact: () => void }) => {
Pay attention to your code style.

2022-04-21 06:19 UTC, su-chang commented on jekyll/_posts/2022-04-20-post-message-for-puppet-walnut.md
> +- 尽可能增加对其他功能的支持
Need more detail info here.

2022-04-21 07:08 UTC, su-chang submitted a review, later dismissed

2022-04-21 11:26 UTC, su-chang submitted a review, later dismissed

2022-04-22 03:59 UTC, fabian4 commented on jekyll/_posts/2022-04-20-post-message-for-puppet-walnut.md
> +~~~ts
I think it works just fine

2022-04-22 04:49 UTC, huan commented on jekyll/_posts/2022-04-20-post-message-for-puppet-walnut.md
> +~~~ts
Could you explain why you use an unusual format of the markdown syntax?

We should keep using one style so that it can be easy understand to everybody.

2022-04-22 06:20 UTC, fabian4 commented on jekyll/_posts/2022-04-20-post-message-for-puppet-walnut.md
> +~~~ts
Now I have changed it for ```

2022-04-22 06:32 UTC, su-chang requested changes

2022-04-22 06:32 UTC, su-chang commented on jekyll/_posts/2022-04-20-post-message-for-puppet-walnut.md
> +  .on('message', async (message: { toContact: () => void }) => {
Why need `{ toContact: () => void }` this interface here?

2022-04-22 11:23 UTC, su-chang submitted a review, later dismissed

2022-04-23 07:38 UTC, fabian4 commented
ping @huan

2022-04-23 07:52 UTC, huan commented on jekyll/_posts/2022-04-20-post-message-for-puppet-walnut.md
> +![image-message](https://user-images.githubusercontent.com/60428924/163546352-1d573b86-65ee-474e-baf3-008ffe608a8d.jpg)
Please save the image file to local assets folder to ensure it will not be 404 in the future.

2022-04-23 10:06 UTC, huan approved these changes
LGTM

2022-04-24 04:19 UTC, su-chang approved these changes

2022-04-24 09:24 UTC, IronConrad approved these changes
OK

2022-04-24 23:56 UTC, merged