How to use Puppet-Walnut
wechaty/jekyll pull request #118
Opened 2022-04-22 10:36 UTC by fabian4

related issue: https://github.com/wechaty/puppet-walnut/issues/32

2022-04-22 11:05 UTC, su-chang commented on jekyll/_posts/2022-04-22-how-to-start-puppet-walnut.md
> +  - plan
Could you please explain why set `plan` as a tag here?

2022-04-22 11:20 UTC, su-chang requested changes

2022-04-22 11:20 UTC, su-chang commented on jekyll/_posts/2022-04-22-how-to-start-puppet-walnut.md
> +> 在完成第二步的硬核桃开发者套件申请试用后，我们已经有了从硬核桃5G开发者社区申请到的Chatbot的AppId、Chatbot的AppKey、Chatbot的sipId。上报填报chatbot的公网回调地址
Need more detail info here.

2022-04-22 11:20 UTC, su-chang commented on jekyll/_posts/2022-04-22-how-to-start-puppet-walnut.md
> +#### 1. 设置我们的环境变量
Please remove `我们的`.

2022-04-22 11:20 UTC, su-chang commented on jekyll/_posts/2022-04-22-how-to-start-puppet-walnut.md
> +#### 2. 安装我们的依赖
Please remove `我们的`.

2022-04-22 11:20 UTC, su-chang commented on jekyll/_posts/2022-04-22-how-to-start-puppet-walnut.md
> +  .on('login',            (user: any) => log.info(`User ${user} logged in`))
Pay attention to your code style.

2022-04-22 11:20 UTC, su-chang commented on jekyll/_posts/2022-04-22-how-to-start-puppet-walnut.md
> +- 将我们之前上报的公网回调地址**映射到我们本地的3000端口**。
Please make it more clear, an example could be better.

2022-04-22 14:54 UTC, huan requested changes

2022-04-22 14:54 UTC, huan commented on jekyll/_posts/2022-04-22-how-to-start-puppet-walnut.md
> +![image](https://user-images.githubusercontent.com/60428924/164730430-171e74f4-eeb5-432b-aefc-f34ef35ac25b.png)
Please save assets file to local folders instead of using URL, for prevent future 404 errors.

2022-04-23 10:07 UTC, huan approved these changes
LGTM

2022-04-24 03:58 UTC, su-chang approved these changes

2022-04-24 04:13 UTC, fabian4 commented
ping @huan @lijiarui @IronConrad

2022-04-24 04:26 UTC, huan commented
I have no more comments, thank you very much.

2022-04-24 06:21 UTC, IronConrad approved these changes
OK

2022-04-24 23:57 UTC, huan approved these changes
LGTM

2022-04-25 04:13 UTC, merged