Feat/update wxwork blog
wechaty/jekyll pull request #148
Opened 2022-12-28 09:08 UTC by hcfw007

编辑已有blog，默认模板不适用。

2022-12-28 09:36 UTC, windmemory submitted a review, later dismissed
LGTM

2022-12-28 09:40 UTC, lijiarui requested changes

2022-12-28 09:40 UTC, lijiarui commented on jekyll/_posts/2020-12-07-puppet-wxwork-beta-release.md
>  想要使用的，请点击[wxwork 购买链接](https://qiwei.juzibot.com/user/login?isWechaty=true) 购买吧！
We should remove `https://qiwei.juzibot.com/user/login?isWechaty=true` here

2022-12-28 09:59 UTC, hcfw007 commented on jekyll/_posts/2020-12-07-puppet-wxwork-beta-release.md
>  想要使用的，请点击[wxwork 购买链接](https://qiwei.juzibot.com/user/login?isWechaty=true) 购买吧！
done

2023-01-18 09:16 UTC, hcfw007 commented on jekyll/_posts/2020-12-07-puppet-wxwork-beta-release.md
> +~~想要使用的，请点击wxwork 购买链接购买吧！~~
done

2023-01-18 10:56 UTC, lijiarui requested changes
Please only commit related files to this PR

2023-01-18 10:56 UTC, lijiarui commented on src/jekyll/get-frontmatter-avatar-list.ts
> +    return [ front['avatar'] ]
Why do you add this changes to this PR? @hcfw007

2023-01-18 11:19 UTC, hcfw007 commented on src/jekyll/get-frontmatter-avatar-list.ts
> +    return [ front['avatar'] ]
Because @chatie/eslint-config has been updated and it now requires array-bracket-spacing, see https://eslint.org/docs/latest/rules/array-bracket-spacing

2023-01-18 12:46 UTC, lijiarui commented on src/jekyll/get-frontmatter-avatar-list.ts
> +    return [ front['avatar'] ]
Good job

2023-01-18 12:46 UTC, merged