好室友机器人升级为企业微信, 结合使用ChatGPT
wechaty/jekyll pull request #163
Opened 2023-05-21 13:46 UTC by aishiqi

Please make sure to check the following boxes creating your pull request, thank you very much!

- [x] Add Blog Header, including title, author, image, categories, tags, etc.  

    For example:  

    ```md
    ---
    title: Your Great Blog Title
    author: your_github_id
    categories: project
    tags:
      - python
      - padlocal
    image: /assets/2021/02-your-blog-slug/teaser.jpg
    ---

    One line bio

    Your blog post content Your blog post content
    Your blog post content Your blog post content
    Your blog post content Your blog post content
    ```

    > It will be easier to start drafting your post by using a existing post file as your template, for example, [this one](https://github.com/wechaty/wechaty.js.org/blob/master/jekyll/_posts/2021-01-14-wechaty-puppet-service.md)

- [x] Keep all filenames lowercase, and use `-` to connect words instead of space. e.g. `2017-10-06-wechat-pc-impactor.md` instead of `2017-10-06-WeChat PC Impactor.md`
- [x] Embed video/pdf from YouTube/Bilibili/local (if there's any) by using `{% include iframe.html src="URL_or_PATH" %}`. (Learn more about how to embed file/url in the post by reading this [blog post](https://wechaty.js.org/2020/08/24/add-video-to-wechaty-blog/)
- [x] Save photo to local before publishing, to a folder named by `${MONTH}-${YOUR_BLOG_SLUG}/` under `/assets/2021/` directory.
- [x] Select a beautiful and meaningful teaser image for your blog
- [x] Create your contributor profile (if you are a first time contributor)

    For excample:

    > jekyll/_contributors/lijiarui.md

    ```yaml
    ---
    name: Jiarui LI (李佳芮)
    site: https://lijiarui.github.io
    bio: 句子互动创始人 & CEO，微软人工智能最具价值专家 (AI MVP)
    avatar: /jekyll/assets/contributors/lijiarui/avatar.png
    email: rui@juzi.bot
    twitter: https://weibo.com/u/2175505900
    ---
    ```

  Here is the example file:

  - lijiarui.md: <https://github.com/wechaty/jekyll/blob/main/jekyll/_contributors/lijiarui.md>
  - It will shown like this on wechaty website: <https://wechaty.js.org/contributors/lijiarui/>

To learn more about the contribute guideline, visit: <https://wechaty.js.org/docs/contributor-program/>

2023-05-21 13:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/wechaty/jekyll?pullRequest=163) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/wechaty/jekyll?pullRequest=163) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/wechaty/jekyll?pullRequest=163) it.</sub>

2023-06-05 06:58 UTC, huan commented on jekyll/_posts/2023-05-21-haoshiyou-bot-upgrade-to-wecom.md
> +"@juzi/wechaty": "^1.0.52",
Can we use the official Wechaty npm for this project?

2023-06-05 07:19 UTC, huan commented
Please make sure the following requirements have been met for your PR before we can continue reviewing it:

2. The PR has passed all the CI tests and turned _green_. (you can execute all tests locally by running `npm test`)

2023-06-05 10:24 UTC, aishiqi commented
> Please make sure the following requirements have been met for your PR before we can continue reviewing it:
> 
> 2. The PR has passed all the CI tests and turned _green_. (you can execute all tests locally by running `npm test`)

Done, passed the test.

2023-06-05 10:28 UTC, aishiqi commented on jekyll/_posts/2023-05-21-haoshiyou-bot-upgrade-to-wecom.md
> +"@juzi/wechaty": "^1.0.52",
Sure, I tested, both of them works.
The Juzi version may have some extra features.
For example, it support those extra events:
```Text
post-comment
post-tap
room-announce
tag
tag-group
```

I've just updated the blog to explain it.

2023-06-05 17:02 UTC, huan requested changes

2023-06-05 17:02 UTC, huan commented on jekyll/_posts/2023-05-21-haoshiyou-bot-upgrade-to-wecom.md
> +"@juzi/wechaty": "^1.0.52",
Can we use the community npm package instead of an unofficial one?

2023-06-05 18:29 UTC, aishiqi commented on jekyll/_posts/2023-05-21-haoshiyou-bot-upgrade-to-wecom.md
> +"@juzi/wechaty": "^1.0.52",
Sure, Removed the unofficial wechaty related content.

2023-06-12 05:16 UTC, huan approved these changes
LGTM

2023-06-12 05:17 UTC, merged

2023-06-12 05:17 UTC, huan commented
Thank you very much for your contribution!

## You are welcome to join [Wechaty Contributor Program](https://wechaty.js.org/docs/contributor-program/)

### 1. Join Wechaty Organization

> 

I have invited you to join our Wechaty GitHub Organization, please accept it by following the above message. (See also: [wechaty/PMC#16](https://github.com/wechaty/PMC/issues/16))

### 2. Update Your Wechaty Contributor Profile

1. Please open [Contributor Hall of Fame](https://docs.google.com/spreadsheets/d/1XcDoIczyIclqXP1p90Sz7S0n4Q22xjFzJmjPFlU2g1E/edit#gid=0) and add yourself to the end of the list, so that other contributors will know you better!
1. Please add yourself to our Website [Contributors](https://wechaty.js.org/contributors/) by [creating a PR](https://github.com/wechaty/jekyll/tree/main/jekyll/_contributors) and refer to this PR link as well.

### 3. Join The Contributor Only WeChat Room

We also have a WeChat room for contributors only which can discuss Wechaty at a deeper level, you are welcome to join and if you are interested.

Please add @lijiarui wechat: _ruirui_0914_ and send her this pr link. She will invite you into Wechaty Contributor Room

Cheers!